version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - boilertime

  boilertime:
    image: mapldx/boilertime:latest
    container_name: boilertime
    expose:
      - 8443

networks:
  nginx_network:
    name: nginx_network
    external: true