name: Deploy optimizer to ubuntu-s-2vcpu-2gb-nyc1-01

on:
  push:
    branches:
      - main
      - sprint-3-user-story-8

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t mapldx/boilertime:latest .

    - name: Push Docker image
      run: docker push mapldx/boilertime:latest

    - name: Add server public key to known hosts
      run: ssh-keyscan 159.203.177.25 >> ~/.ssh/known_hosts

    - name: Deploy and run Docker container
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key_rsa
        chmod 600 private_key_rsa
        scp -i private_key_rsa ./deploy.sh root@159.203.177.25:/root
        ssh -i private_key_rsa root@159.203.177.25 'bash -s' < ./deploy.sh
        rm -f private_key_rsa