name: Trigger deployment

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit empty change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Trigger deployment for pull request #${{ github.event.number }}"
          git push origin main
