name: Trigger deployment

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit empty change
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --local user.email "alpinemail@zsy.sh"
          git config --local user.name "Zachary Will Sy"
          git commit --allow-empty -m "Trigger deployment for pull request #${{ github.event.number }}"
          git push origin main
